### ISSUE TITLE
Line 113 in data.py should be np.allclose(...) not np.all_close(...)

### ISSUE THREAD

**Issue by mhunterklein** [carlson-lab/lpne#14]
Not sure if this is a numpy version issue on my end, but I'm seeing that the function call is as stated in the title. https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

**Comment by jackgoffinet** [comment]
Thanks, Hunter. I fixed this bug in the last commit: [10a2f84](https://github.com/carlson-lab/lpne/commit/10a2f840ed354f71c2e015b3c5f6447199e6d99d)
