### ISSUE TITLE
Error with averaging channels

### ISSUE THREAD

**Issue by Noah-Lanier** [carlson-lab/lpne#15]
While attempting to make features from the social data, I encountered an issue with averaging the channels of some of the lfp files. The error that occurred was:
'AssertionError: No channels to make grouped channel Cx_Cg!'.

However, there is a channel in the lfp files which, from the channel map, should average into that area.

I've put files to replicate this error on the DCC at /datacommons/carlsonlab/nwl3/error_example. I include the pipeline that I use, as well as two folders containing the files needed to either replicate the error (the error folder) or show that the pipeline works in other cases (the counterexample folder).

Please let me know if you need any more information, thanks.

**Comment by jackgoffinet** [comment]
Hi Noah, from [this](https://github.com/carlson-lab/lpne/blob/10a2f840ed354f71c2e015b3c5f6447199e6d99d/lpne/preprocess/channel_maps.py#L80) line, it looks like you are passing `assert_onto=True`, which is probably safest. Could you catch this error or figure out which file is running into issues and then print both the channel map that you're passing and list of the channels, `list(lfps.keys())`?

**Comment by jackgoffinet** [comment]
@Noah-Lanier , were you able to look at this?

**Comment by Noah-Lanier** [comment]
Here is the list of channels for a file that causes an error:
['NAc_Core_04', 'NAc_Core_03', 'NAc_Core_02', 'NAc_Core_01', 'NAc_Shell_04', 'NAc_Shell_03', 'NAc_Shell_02', 'NAc_Shell_01', 'Amy_CeA_02', 'Amy_CeA_01', 'Amy_BLA_04', 'Amy_BLA_03', 'Amy_BLA_02', 'Amy_BLA_01', 'Hipp_03', 'Hipp_02', 'Hipp_01', 'VTA_L_02', 'VTA_L_01', 'VTA_R_02', 'VTA_R_01', 'MD_Thal_02', 'MD_Thal_01', 'PrL_Cx_R_01']


Here is the list of channels for a file that does not cause an error:
['NAc_Core_04', 'NAc_Core_03', 'NAc_Core_02', 'NAc_Core_01', 'NAc_Shell_03', 'NAc_Shell_02', 'NAc_Shell_01', 'Amy_CeA_02', 'Amy_CeA_01', 'Amy_BLA_04', 'Amy_BLA_03', 'Amy_BLA_02', 'Amy_BLA_01', 'Hipp_03', 'Hipp_02', 'Hipp_01', 'VTA_L_02', 'VTA_L_01', 'VTA_R_02', 'VTA_R_01', 'MD_Thal_03', 'MD_Thal_02', 'MD_Thal_01', 'IL_Cx_R_01', 'PrL_Cx_R_01', 'Cg_Cx_R_02', 'Cg_Cx_R_01', 'IL_Cx_L_01', 'PrL_Cx_L_01', 'Cg_Cx_L_02', 'Cg_Cx_L_01']


Here is the channel mapping:

[ChannelNames.xlsx](https://github.com/carlson-lab/lpne/files/11267370/ChannelNames.xlsx)

**Comment by jackgoffinet** [comment]
@Noah-Lanier, the first file is causing an error because there aren't any channels to make Cx_Cg or Cx_IL, which are the values of the channel map dictionary. It's possible these channels were dropped in the CHANS files or that they aren't in the original LFP files.

**Comment by Noah-Lanier** [comment]
Huh, I guess I misread the output somehow, sorry about that.
